### ISSUE TITLE
[Bug] document.body removeEvent 문제

### ISSUE THREAD

**Issue by seoko97** [woowa-techcamp-2022/web-todo-7#20]
# [Bug] document.body removeEvent 문제
document.body에 등록된 이벤트가 제거되지 않습니다.

## 설명
- todo 변경 이벤트 실행중 onmouseup 이벤트가 실행된다면 body에 등록된 이벤트가 삭제되어야 합니다.
- 하지만 삭제되지 않고 반복적으로 이벤트가 생성됩니다.

## etc
<img width="408" alt="image" src="https://user-images.githubusercontent.com/60173534/178764857-876a9903-7eed-49f6-b7b6-d7c52f85deb6.png">

**Comment by sangrimlee** [comment]
제가 로컬에서 실행해 볼 수 있게 지금 작업 중이신 브랜치를 push 해 주실 수 있나요?

**Comment by seoko97** [comment]
버그가 있는상태로 코드를 업로드할까요?

**Comment by seoko97** [comment]
문제
- removeEvent와
