### ISSUE TITLE
[Style] CSS 컨벤션 정하기

### ISSUE THREAD

**Issue by sangrimlee** [woowa-techcamp-2022/web-todo-7#7]
# [Style] CSS 컨벤션 정하기

CSS 클래스 네이밍 컨벤션 정하기

## 설명
- CSS 클래스 네이밍 컨벤션 정하기
- BEM, OOCSS, SMACSS등 CSS 방법론 찾아보고, 어떤 것을 할 지 정하기

**Comment by sangrimlee** [comment]
BEM 방법론으로 한다면, TodoSection의 클래스 네임은 어떻게하면 될까요?

제 생각은
```css
.todo-section

.todo-section__header

.todo-section__header--left

.todo-section__header--right

.todo-section__title

.todo-section__count

.todo-section__icon
```

**Comment by seoko97** [comment]
넵 확인했습니다! 지금 도착해서 시작하려 합니다ㅠ
